Remove hooks/utils
Given that pre-commit is started from a different directory than
the pre-commit-hooks directory, it takes some legwork to change
and then change back to user's code directory.

Instead of having shared utils, each script should take of itself
and not use shared functions. This results in duplicate code,
but it's only 5 lines each.

diff --git a/hooks/clang-format b/hooks/clang-format
--- a/hooks/clang-format
+++ b/hooks/clang-format
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 # Wrapper script for clang-format
+CMD="clang-format"
+if [ -z "$(command -v $CMD)" ]; then
+	echo -e "ERR: $CMD not found.\nMake sure to install $CMD and add it to your path."
+	echo -e "For more info: https://github.com/pocc/pre-commit-hooks#prerequisites"
+	exit 1
+fi
 
-. hooks/utils
-
-check_exists clang-format
 orig_file="${*: -1}"
 # pre-commit will fail if there are file changes due to formatting if the user
 # enters arg `-i` (change in place).
diff --git a/hooks/clang-tidy b/hooks/clang-tidy
--- a/hooks/clang-tidy
+++ b/hooks/clang-tidy
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 # Wrapper script for clang-tidy
+CMD="clang-tidy"
+if [ -z "$(command -v $CMD)" ]; then
+	echo -e "ERR: $CMD not found.\nMake sure to install $CMD and add it to your path."
+	echo -e "For more info: https://github.com/pocc/pre-commit-hooks#prerequisites"
+	exit 1
+fi
 
-. hooks/utils
-
-check_exists clang-tidy
 # Split text into an array of args that can be passed into clang-tidy
 # tee because of weird stdout issues with clang-tidy
 output="$(clang-tidy "$@" 2>/dev/null | tee)"
diff --git a/hooks/oclint b/hooks/oclint
--- a/hooks/oclint
+++ b/hooks/oclint
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
 # Wrapper script for oclint
-
-. hooks/utils
-
-check_exists oclint
+CMD="oclint"
+if [ -z "$(command -v $CMD)" ]; then
+	echo -e "ERR: $CMD not found.\nMake sure to install $CMD and add it to your path."
+	echo -e "For more info: https://github.com/pocc/pre-commit-hooks#prerequisites"
+	exit 1
+fi
 
 pwd_files="$(ls)"
 # Split text into an array of args that can be passed into oclint
