hooks/oclint now returns 1 if there is an error

diff --git a/hooks/oclint b/hooks/oclint
--- a/hooks/oclint
+++ b/hooks/oclint
@@ -8,6 +8,16 @@ check_exists oclint
 pwd_files="$(ls)"
 # Split text into an array of args that can be passed into oclint
 IFS=" " read -r -a args <<< "$(clean_args "$@")"
-oclint "${args[@]}"
+output="$(oclint "${args[@]}")"
+echo -e "${output}"
 # Remove any plist files generated by oclint
 echo "$pwd_files $(ls)" | tr ' ' '\n' | sort | uniq -u | grep .plist | xargs rm
+
+# oclint return code is usually wrong (github.com/oclint/oclint/issues/538)
+# Figure out what it is based on stdout and return that instead
+no_errors="FilesWithViolations=0"
+if grep -q $no_errors <<<"$output"; then
+	exit 0
+else
+	exit 1
+fi
